#!/bin/bash
# Fame - Fine automated minecraft exports
# Written by Christer Jonassen
# Licensed under CC BY-NC-SA 3.0 (check LICENCE file or http://creativecommons.org/licenses/by-nc-sa/3.0/ for details.)
# Made possible by the wise *nix people sharing their knowledge online
#
# Check README for instructions


# Variables
APPVERSION="0.1"
APPNAME="Fame"
REDRAW="YES"
PREVIOUSCOLUMNS=`tput cols`
PREVIOUSLINES=`tput lines`
# Pretty colors for the terminal:
DEF="\x1b[0m"
WHITE="\e[0;37m"
LIGHTBLACK="\x1b[30;01m"
BLACK="\x1b[30;11m"
LIGHTBLUE="\x1b[34;01m"
BLUE="\x1b[34;11m"
LIGHTCYAN="\x1b[36;01m"
CYAN="\x1b[36;11m"
LIGHTGRAY="\x1b[37;01m"
GRAY="\x1b[37;11m"
LIGHTGREEN="\x1b[32;01m"
GREEN="\x1b[32;11m"
LIGHTPURPLE="\x1b[35;01m"
PURPLE="\x1b[35;11m"
LIGHTRED="\x1b[31;01m"
RED="\x1b[31;11m"
LIGHTYELLOW="\x1b[33;01m"
YELLOW="\x1b[33;11m"


fametext=""$PURPLE"F"$YELLOW"."$PURPLE"A"$YELLOW"."$PURPLE"M"$YELLOW"."$PURPLE"E""$DEF"

gfx()
{
	case "$1" in
		
		splash)
			clear
			echo
			echo
			echo
			echo          
			echo
			echo
			echo
			echo -e ""$LIGHTPURPLE"                ::::::::::       :::           :::   :::       :::::::::    "
			echo -e ""$PURPLE"               :+:            :+: :+:        :+:+: :+:+:      :+:           "
			echo -e ""$PURPLE"              +:+           +:+   +:+      +:+ +:+:+ +:+     +:+            "
			echo -e ""$PURPLE"             :#::+::#     +#++:++#++:     +#+  +:+  +#+     +#++:++#        "$DEF""
			echo -e ""$PURPLE"            +#+          +#+     +#+     +#+       +#+     +#+              "
			echo -e ""$PURPLE"           #+#          #+#     #+#     #+#       #+#     #+#               "
			echo -e ""$PURPLE"          ###      "$YELLOW" * "$PURPLE" ###     ### "$YELLOW" * "$PURPLE" ###       ### "$YELLOW" * "$PURPLE" ##########         "
			echo
			echo -e ""$WHITE"                    Fine "$LIGHTBLACK"-"$WHITE" Automated "$LIGHTBLACK"-"$WHITE" Minecraft "$LIGHTBLACK"-"$WHITE" Exports"
			echo
			echo
			echo -e "                          "$LIGHTBLACK"Cj Designs/"$LIGHTBLACK"CSDNSERVER.COM"$DEF""
			echo
			echo
			echo
			sleep 2
			clear
			;;

		header)
			clear
			timeupdate
			echo -e "$fametext"$WHITE" build $APPVERSION - $HMS" 
			echo -e "0 Successful backups, 49 Warnings, 2 Errors"$DEF""
			gfx line
			echo
			;;

		line)
			echo -e ""$DEF""$PURPLE"--------------------------------------------------------------------------------"$DEF""
			;;

		termreset)
			echo Terminal size changed, resetting...
			PREVIOUSCOLUMNS=`tput cols`
			PREVIOUSLINES=`tput lines`
			REDRAW=YES
			reset
			gfx header
			;;
	esac


}

timeupdate() # Sets current time into different variables. Used for timestamping etc.
{
	DATE=$(date +"%d-%m-%Y")
	UNIXSTAMP=$(date +%s)
	BKSTAMP=""$SERVERSCREEN"_backup_$(date +"%m-%d-%Y")_$(date +"%Hh%Mm%Ss")_fbck.tar.gz"
	NOWSTAMP=$(date +"%Hh%Mm%Ss")
	HM=$(date +"%R")
	HMS=$(date +"%R:%S")
	HOUR=$(date +"%H")
	MINUTE=$(date +"%M")
	SEC=$(date +"%S")
}



startup()
{
	echo lol
}


fameprocess()
{
			while read HOSTENTRY ; do

				SERVERDESC=`echo $HOSTENTRY | awk -F":" '{print $1}' $2`
				SERVERSCREEN=`echo $HOSTENTRY | awk -F":" '{print $2}' $2`
				SERVERPATH=`echo $HOSTENTRY | awk -F":" '{print $3}' $2`
			
			done < world.lst
}



backup()
{
	screen -x $SERVERSCREEN -X stuff "`printf "save-off\r"`"
	tar -cpvzf $SERVERPATH/../backup/$SERVERSCREEN-backup_.tar.gz $SERVERPATH
	world1-11-01-2013-20h31m39s.tar.gz

	screen -x $SERVERSCREEN -X stuff "`printf "save-on\r"`"

}

#mc()
#{
#	case "$1" in
#	save-on)
#		echo lol
#		;;
#
#		save-off)
#		echo lol
#		;;
#}

notify()
{
	case "$1" in
		mc)
		screen -x $SERVERSCREEN -X stuff "`printf "say $2\r"`"
		;;

		log)
		echo "[$HMS] $2">>fame.log
		;;

		console)
		#echo lol
		;;

		*)
		notify mc "$1"
		notify log "$1"
		notify console "$1"
		;;
#	screen -x $SCREENNAME -X stuff "`printf "say Startar oppbakking av verda\r"`"
	esac
}


exporting()
{
	echo lol
}


upload()
{
	echo lol
}


archive()
{
	echo lol
}


cleanup()
{
	echo lol
}


#actual runscript

clear
gfx splash # Display splash screen with logo
gfx header
fameprocess
echo -e ""$YELLOW"Server Description"
Server Description           Screen                 Current status
World 1                      mc-world1              Informing users
													Exporting via           
echo
echo "SERVERDESC: $SERVERDESC"
echo "SCREENNAME: $SERVERSCREEN"
echo "SERVERPATH: $SERVERPATH"
echo
timeupdate
echo "Backupstamp: $BKSTAMP"

notify "Fame test @ $NOWSTAMP"
